swim_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  wheel_left_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_active_left_2_base_link
  wheel_right_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_active_right_2_base_link